# Site settings
title: Tony Teng blog
email: slooowtyk@outlook.com
description: "Life is hard."
baseurl: ""
url: "http://slooowtyk.github.io"
#blogurl: "http://yihui-he.github.io/blog"
#twitter_username: karpathy
github_username:  sloooWTYK

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
